Login 기능 리팩토링
INU-CapstoneDesign/INU-Festival-FE pull request #112
Opened 2024-03-14 02:12 UTC by hxxzxx

# 해결햐려는 문제가 무엇인가요? 🤔

* 불필요한 로그인 컴포넌트
* 주석
* br태그 

# 어떻게 해결하셨나요? 🔑

* div -> span 태그로 변경 후 br 태그 제거
* 불필요한 로그인 버튼 컴포넌트 삭제
* 주석 삭제 

# 어떤 부분을 리뷰 받았으면 좋겠나요? 🛠️

* 수정하지 않은 오류가 있으면 말씀해주세요

# 추가로 남길 메모가 있으신가요? 📝

* 

## Attachment 📸

* 이번 MR의 Front 동작의 이해를 돕는 GIF 파일 첨부!
* 리뷰어의 이해를 돕기 위한 모듈/클래스 설계에 대한 Diagram 포함!

2024-03-18 07:08 UTC, kaori-killer requested changes

2024-03-18 07:08 UTC, kaori-killer commented on src/components/Login/LoginForm.tsx
> +        학생은 학번, 교원은 교번, 직원은 사번입니다.
문자열을 중괄호로 감싸는 방법을 선택한 이유가 있을까요?

한 줄에 하나의 문장을 보여주고 싶다면, p태그를 쓰는 게 더 깔끔하지 않을까요?

지금은 코드만 봤을 때는 어떤 결과로 보일지 예상이 잘 안되는 것 같아요!

2024-03-18 11:56 UTC, hxxzxx commented on src/components/Login/LoginForm.tsx
> +        학생은 학번, 교원은 교번, 직원은 사번입니다.
css에서 white-space:pre-line를 이용하면 한줄에 한 개씩 보여서 이걸 이용하기 위해 중괄호를 감쌌습니다. 중괄호로 감싸지 않으면 안먹더라구요!

2024-03-19 02:49 UTC, kaori-killer commented on src/components/Login/LoginForm.tsx
> +        학생은 학번, 교원은 교번, 직원은 사번입니다.
맞습니다. pre-line은 개행 문자를 인식할 수 있도록 하는데, `로그인 정보는 포탈과 동일합니다{'\n'}` 이런식으로 끝에 직접 개행문자를 넣지 않으면 개행이 없어서 처리를 안하는 것 같습니다.

그래서 중괄호를 이용해서 개행 문자를 넣어주신 것 같아요!

저는 아래 방법을 추천드리는데요, 정답이 없는 부분이라 희주님이 생각하시는 방향으로 선택하시면 될 것 같아요. 지금 방법을 유지하는 것도 좋고요. 방법 선택하시고 답글 남겨주시면 머지하겠습니다 😊 

```css
const Detail = styled.div`
  color: #CFCFCF;
  text-align: center;
  font-family: "SF Pro";
  font-size: 13px;
  font-style: normal;
  font-weight: 400;
  line-height: 19px; 
  letter-spacing: -0.52px;
  margin-top:60px;
  white-space: pre-line;

  span {
    display: block;
  }
```

```jsx
      <Detail>
        <span>로그인 정보는 포탈과 동일합니다</span>
        <span>학생은 학번, 교원은 교번, 직원은 사번입니다.</span>
        <span>아이디 찾기 / 비밀번호 찾기는</span>
        <span>PC에서 포탈을 이용하시기 바랍니다.</span>
      </Detail>
```

2024-03-20 09:14 UTC, hxxzxx commented on src/components/Login/LoginForm.tsx
> +        학생은 학번, 교원은 교번, 직원은 사번입니다.
이렇게 변경했습니당

2024-03-21 07:12 UTC, kaori-killer approved these changes
고생하셨습니다 :)

2024-03-21 07:12 UTC, merged