좋아요를 누르면 화면에서 숫자가 올라간다.
INU-CapstoneDesign/INU-Festival-FE pull request #120
Opened 2024-03-20 14:11 UTC by hxxzxx

# 해결햐려는 문제가 무엇인가요? 🤔
* 사용자가 좋아요를 누르면 화면에서 숫자가 올라간다.
* 좋아요 상태를 외부에서 관리한다.
* 사용자가 좋아요를 누른 후 페이지를 이동할 때 좋아요 카운트 수를 백엔드에게 데이터를 전송한다.

# 어떻게 해결하셨나요? 🔑
* 페이지 이동할 때 데이터 전송을 구현하지 못해 단순히 네비바에 있는 타임테이블을 누르면 데이터를 전송하는 것으로 구현했습니다.
* 좋아요수가 화면상에서 보여지게 하기 위해 useState,useEffect를 이용해 구현했습니다.

# 어떤 부분을 리뷰 받았으면 좋겠나요? 🛠️
* DetaildeMapPage.tsx, BoothRanking.tsx의 좋아요 부분
* ApiService.ts, LikeStore.ts,useLikeStore.ts
* 좋아요수를 누를때 화면에서 올라가는 것을 보이게 하기위해 useState,useEffect를 이용했는데 상태관리를 외부에서 하는게 아닌 내부에서 해서 다른 방법이 있는지 궁금합니다.

# 추가로 남길 메모가 있으신가요? 📝
* 사용자가 좋아요를 누른 후 페이지를 이동할 때 백엔드에게 보내는 부분을 구현하지 못했습니다.
* 사용자가 여러개의 부스 좋아요를 누른 후 페이지를 이동할때 어떻게 데이터를 보내야할지 고민 중입니다.
* 좋아요를 눌렀을때 각 부스의 아이디를 비교해야할까요? 
* 페이지를 이동할 때 이동 감지를 어떻게 하는건지 감이 안옵니다. -> useLocation을 사용해야할까요?

## Attachment 📸

* 이번 MR의 Front 동작의 이해를 돕는 GIF 파일 첨부!
* 리뷰어의 이해를 돕기 위한 모듈/클래스 설계에 대한 Diagram 포함!

2024-03-21 07:22 UTC, kaori-killer requested changes
질문에 대한 대답 부탁드립니다~!

2024-03-21 07:22 UTC, kaori-killer commented on src/components/Main/BoothRanking.tsx
> +import { useEffect, useState } from 'react';
사소한 부분이지만, 호출하는 부분도 순서가 일관되면 좋을 것 같습니다. 

외부 라이브러리 훅
useState, useRef
커스텀훅
함수
useEffect

2024-03-21 07:22 UTC, kaori-killer commented on src/components/Main/BoothRanking.tsx
> +  const [likeCounts, setLikeCounts] = useState<{ [key: string]: number }>({});
외부 Store에서 좋아요를 관리하는데 내부에서 한번더 관리하는 이유가 있을까요?

2024-03-21 07:35 UTC, hxxzxx commented on src/components/Main/BoothRanking.tsx
> +  const [likeCounts, setLikeCounts] = useState<{ [key: string]: number }>({});
외부 Store에서는 좋아요를 몇번 눌렀는지를 관리하고 있는데 화면상에서는 DB에서 받아온 좋아요 수를 가져와서 +1씩 해야했고 그 방법을 useState와 useEffect를 이용하는 방법밖에 떠오르지 않았습니다. 화면상에서 받아온 좋아요수를 +1하는 방법을 그 방법 쓰지 않고 하는 방법이 있는지 궁금합나다.

2024-03-21 07:46 UTC, kaori-killer requested changes

2024-03-21 07:46 UTC, kaori-killer commented on src/services/ApiService.ts
> +    console.log(response.data);
console.log는 PR에 올리지 말아주세요~!

2024-03-21 07:46 UTC, kaori-killer commented on src/store/LikeStore.ts
> +    console.log(id, this.liked);
console.log 제거 부탁드립니다~!

2024-03-21 08:05 UTC, kaori-killer requested changes

2024-03-21 08:05 UTC, kaori-killer commented on src/components/Main/BoothRanking.tsx
> +      const initialLikeCounts = {};
혹시 타입 에러 발생 안하나요? 저는 타입에러가 나는데 확인 한번 부탁드립니다.

이 타입은 useState로 좋아요를 만들 때도 쓰여서, 이렇게 타입을 빼면 여기저기서 쓸 수 있을 것 같아요.

```tsx
type LikeCountsType = {
  [key: string]: number;
}
```

2024-03-21 08:11 UTC, kaori-killer requested changes
> 페이지 이동할 때 데이터 전송을 구현하지 못해 단순히 네비바에 있는 타임테이블을 누르면 데이터를 전송하는 것으로 구현했습니다.

좋아요 10번 누르고 타임테이블로 이동하고 메인 페이지로 돌아왔는데, 좋아요 수가 증가하지 않았습니다. 초기 값으로 돌아갔습니다. 이. 부분은 구현이 안된 건가요?

> 페이지를 이동할 때 이동 감지를 어떻게 하는건지 감이 안옵니다. -> useLocation을 사용해야할까요?

사용자가 페이지를 이동하는 부분을 체크하려면 Layout 컴포넌트에서 하면 됩니다.
페이지가 전환되면 항상 Layout 컴포넌트를 사용하기 때문입니다.

이 부분이 이해가 안된다면 이따가 회의 시간에 얘기해봅시다~

2024-03-22 11:16 UTC, hxxzxx commented on src/components/Main/BoothRanking.tsx
> +      const initialLikeCounts = {};
이 부분은 기능이 사라져서 코드 삭제했습니다

2024-03-25 05:22 UTC, kaori-killer commented
수정 완료하시면 다시 댓글 남겨주시고 Slack에서 언급 부탁드립니다~!

2024-03-26 11:23 UTC, kaori-killer approved these changes

2024-03-26 11:28 UTC, merged