Notice page header
INU-CapstoneDesign/INU-Festival-FE pull request #57
Opened 2024-01-05 01:35 UTC by snsdl0905

# 해결햐려는 문제가 무엇인가요? 🤔

* 알림 센터(공지사항) 페이지의 헤더를 만들었다.
* 메인페이지의 알림 센터 아이콘을 바꾸고 연결했다.

* 페이지의 이름만 바뀐 채로 헤더가 재사용되어서 컴포넌트로 분리했는데, 메인의 헤더와는 달라서 헤더의 이름을 어떻게 해야할 지 모르겠다.
* 메인의 헤더와 크기 및 위치는 같게 헤야할 것 같은데 디자인에 비해서 아래 여백이 커보이는 것 같다.

# 어떻게 해결하셨나요? 🔑

* 일단은 메인페이지의 헤더에 위치와 크기를 맞추고, PageHeader로 분리했습니다.

## Attachment 📸

* 이번 MR의 Front 동작의 이해를 돕는 GIF 파일 첨부!
* 리뷰어의 이해를 돕기 위한 모듈/클래스 설계에 대한 Diagram 포함!

![image](https://github.com/snsdl0905/INU-Festival-FE/assets/105384780/6f2317ae-ec1e-49a3-a421-8097c1a535ee)

![image](https://github.com/snsdl0905/INU-Festival-FE/assets/105384780/7925a1f7-8763-4fbe-a0b4-db810dac3c7e)

2024-01-06 15:34 UTC, kaori-killer commented
넘넘 고생했습니다~! 

> 페이지의 이름만 바뀐 채로 헤더가 재사용되어서 컴포넌트로 분리했는데, 메인의 헤더와는 달라서 헤더의 이름을 어떻게 해야할 지 모르겠다.

components 폴더에 Notice 라는 폴더를 만들고 하위에 Header.tsx 만들면 될 것 같아요. 페이지가 늘어날 수록 components 폴더에 파일이 많아져서 헷갈릴 것 같으니, 페이지마다 폴더를 만듭시다!

메인의 헤더와 크기 및 위치는 같게 헤야할 것 같은데 디자인에 비해서 아래 여백이 커보이는 것 같다.

2024-01-06 15:35 UTC, kaori-killer requested changes
components 폴더에 하위 폴더를 생성해주세요 😊

2024-01-06 15:59 UTC, snsdl0905 commented
> components 폴더에 하위 폴더를 생성해주세요 😊

수정했습니다!

2024-01-07 11:36 UTC, kaori-killer commented
> 수정했습니다!

확인했습니다 😊

2024-01-07 11:36 UTC, merged