Profile
INU-CapstoneDesign/INU-Festival-FE pull request #66
Opened 2024-01-18 18:38 UTC by hxxzxx

# 해결햐려는 문제가 무엇인가요? 🤔

* 로그인 전 프로필 화면 구성 코드를 짰습니다.

# 어떻게 해결하셨나요? 🔑
컨포넌트 분리는 이렇게 진행했습니다.
- Pages/ProfilePage
    - Components/profile/ProfileSection
       - Components/profile/UserInfo
       - Components/profile/LoginBtn
   - Components/profile/HelpSection

# 어떤 부분을 리뷰 받았으면 좋겠나요? 🛠️

* Components/profile 폴더 내에 있는 코드들을 점검받고, 보여지는 화면에 부족하거나 놓친 부분이 있는지 위주로 받고싶습니다.

# 추가로 남길 메모가 있으신가요? 📝

*

## Attachment 📸
![Jan-18-2024 11-52-10](https://github.com/hxxzxx/INU-Festival-FE/assets/89375462/268649bf-0540-4236-ad4a-5a3bf146b083)

* 이번 MR의 Front 동작의 이해를 돕는 GIF 파일 첨부!
* 리뷰어의 이해를 돕기 위한 모듈/클래스 설계에 대한 Diagram 포함!

2024-01-19 04:28 UTC, kaori-killer requested changes

2024-01-19 04:28 UTC, kaori-killer commented on src/components/Profile/HelpSection.tsx
> +    <HelpWrapper>
이 부분의 형태가 다음과 같아서

- 지원
  - 친구 찾기
  - 문의하기
  - 링크 공유하기

div 태그말고 ul태그와 li태그를 쓰는 건 어떠세요? 
그리고  li태그 안에 button가 필요하지 않을까요?

2024-01-19 04:28 UTC, kaori-killer commented on src/components/Profile/HelpSection.tsx
> +        <Helplink>문의 하기</Helplink>
'문의 하기'를 '문의하기'로 정정해야 할 것 같아요!

2024-01-19 04:28 UTC, kaori-killer commented on src/components/Profile/HelpSection.tsx
> +width: 375px;
이 부분에서 width와 height는 안 잡거나 100%로 잡아야 할 것 같아요. 
이유는 페이지 하단에 공백이 길어요. 그리고 
다른 페이지에 갔다가 프로필 페이지로 오면 중심이 다른 곳으로 이동해 있어요. 아래 이미지를 보면 네비바가 이동한 걸 볼 수 있어요.
다른 페이지랑 사이즈가 달라서 그런 것 같아요.

* Before
<img width="337" alt="스크린샷 2024-01-19 오후 1 23 59" src="https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/8e00d30e-7312-4844-a245-7f9e468f2fcb">

---

width, height 잡은 것을 없애고, margin-left와 top을 padding: 20px로 바꾼 결과예요. 참고해주세요.

* After

<img width="337" alt="스크린샷 2024-01-19 오후 1 21 49" src="https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/e5630aeb-8fa2-4569-b74d-f5be6d1a6048">

2024-01-22 20:39 UTC, hxxzxx commented on src/components/Profile/HelpSection.tsx
> +        <Helplink>문의 하기</Helplink>
✅

2024-01-22 20:58 UTC, hxxzxx commented on src/components/Profile/HelpSection.tsx
> +    <HelpWrapper>
✅

2024-01-22 20:58 UTC, hxxzxx commented on src/components/Profile/HelpSection.tsx
> +width: 375px;
✅

2024-01-22 21:04 UTC, hxxzxx commented
수정 후 다시 PR 보낼

2024-01-23 01:27 UTC, kaori-killer approved these changes

2024-01-23 01:27 UTC, merged