부스 목록을 추가하고 부스 상세페이지를 연결하였다.
INU-CapstoneDesign/INU-Festival-FE pull request #79
Opened 2024-01-30 08:44 UTC by snsdl0905

# 해결햐려는 문제가 무엇인가요? 🤔

* 부스 상세페이지에 가상데이터가 들어있었고, 부스 상세페이지가 연결이 되어있지 않았습니다.

# 어떻게 해결하셨나요? 🔑

* 부스 상세페이지를 연결하기 위해 부스 목록페이지를 만들었습니다.
* 부스 상세페이지에서 데이터를 받아와서 쓰도록 수정했습니다.

# 어떤 부분을 리뷰 받았으면 좋겠나요? 🛠️

* 컴포넌트 분리해야 할 부분 말해주시면 참고해서 코드 수정하겠습니다.
* 부스 상세페이지를 위해 라우터를 수정했는데 맞는 방식인지 router 파일과, BoothList, DetailedMapPage 파일을 봐주세요.
* 디자인에 수정해야할 부분이 보인다면 말해주세요.

# 추가로 남길 메모가 있으신가요? 📝

* 아직 컴포넌트 분리가 코드 정리가 제대로 되어있지 않습니다. 내일 안에는 최대한 수정해서 다시 보내겠습니다.
* 지도페이지에서 목록을 올릴 때, 드래그로 구현해야하는데 스와이퍼로 구현해서 모바일 화면에서는 슬라이드가 되지 않습니다. 드래그 이벤트를 넣으면 마우스의 위치를 계산해서 위로 드래그, 아래로 드래그를 판단하던데 더 좋은 방법이 있다면 알려주세요 !
* 부스상세페이지에서 id가 1인 부스를 불러오고자했는데 실패해서 비어있습니다. 
* 부스상세페이지에서 아직 이미지는 불러올 수 없습니다.

## Attachment 📸

* 이번 MR의 Front 동작의 이해를 돕는 GIF 파일 첨부!
* 리뷰어의 이해를 돕기 위한 모듈/클래스 설계에 대한 Diagram 포함!

![Jan-30-2024 17-42-32](https://github.com/snsdl0905/INU-Festival-FE/assets/105384780/9ec30470-ba12-41dc-bfe9-ea22cef44362)

2024-01-30 10:45 UTC, kaori-killer commented
저희 디자인 이렇게 바뀌었는데, 이전 디자인으로 작업한 것 같아요 😭

![스크린샷 2024-01-30 오후 7 44 26](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/40b11331-c9cc-475d-bfc8-0fdf83db66dd)

2024-01-30 10:58 UTC, kaori-killer requested changes
부스 상세페이지에서 뒤로 가기 눌렀을 때, 홈이 아닌 부스 리스트 페이지로 이동하게 하는 부분도 추가로 넣어야 할 것 같습니다!

2024-01-30 10:58 UTC, kaori-killer commented on src/components/Map/BannerContent.tsx
> +    &.swiped-up {
[How to Make a Bottom Sheet for Web](https://blog.mathpresso.com/bottom-sheet-for-web-55ed6cc78c00)을 참고해주세요!

아니면 이 부분은 제가 구현해도 될까요?

2024-01-30 11:03 UTC, kaori-killer commented
부스 상세페이지는 src/components/MapDetail 을 만들어서 하는 건 어떠세요? src/components/Map에는 `http://localhost:8080/map/` 에 관련된 컴포넌트만 넣어도 파일이 많아질 것 같아요!

2024-01-30 11:09 UTC, snsdl0905 commented on src/components/Map/BannerContent.tsx
> +    &.swiped-up {
좋습니당.. 그럼 디자인과 뒤로가기 수정하겠습니다!

2024-01-30 11:10 UTC, kaori-killer commented on src/components/Map/BannerContent.tsx
> +import { useState, useEffect } from 'react';
불러오는 순서를 다음과 같이 하면 어떠세요?

1. 외부 라이브러리에서 불러옴
2. 다른 컴포넌트를 불러옴
3. utills, types 폴더에서 불러옴

```typescript
import { useState, useEffect } from 'react';

import { styled } from 'styled-components';

import BoothList from './BoothList';
```

2024-01-31 10:13 UTC, kaori-killer requested changes

2024-01-31 10:13 UTC, kaori-killer commented on src/components/Map/DetailedMapPage.tsx
> +        border-bottom: 2px solid ${(props) => (props.showInstruction ? '#0147C8' : '#CEDCEA')};
지금 이 부분에서 에러가 나고 있어요. 스타일 컴포넌트에 state를 넘겨주는 것보다, JSX에서 state의 boolean 여부에 따라서 태그에 class를 추가해서, class이름으로 css를 제어하는게 더 나은 것 같아요.

2024-01-31 10:13 UTC, kaori-killer commented on src/components/Map/BoothInstruction.tsx
> +  const InstrucionContainer = styled.div`
컴포넌트 안에 스타일 컴포넌트를 작성하면 안됩니다. 스타일 컴포넌트는 밖으로 분리해주세요.

분리가 필요합니다 ⬇️

<img width="726" alt="스크린샷 2024-01-31 오후 7 05 55" src="https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/114977f8-bd02-4cf2-b0f6-66af6bb1a842">

2024-01-31 10:13 UTC, kaori-killer commented on src/components/Map/DetailedMapPage.tsx
> +                  <img src={img} alt={img} />
이미지를 앞에 '/' 붙이면 불러와져요. 근데 이 부분만 왜 안 불러와지는지 모르겠네요. 일단 '/' 붙여서 진행해보세요!

2024-02-01 02:58 UTC, snsdl0905 commented
말씀해주신 부분들 수정했습니다. 수정하다가 새로운 문제가 발생했는데, InfoWithIcon이나 Notice/Header을 재사용할 떄 props를 추가로 받아서 서로 다른 css를 적용하고자 했습니다. 여기에서 small이나 shdow를 받을 때 boolean을 사용하는데, 값을 넘기는 부분에서 콘솔창에 경고가 뜨는 것 같습니다. 어떻게 수정해야할 지 잘 모르겠습니다.

2024-02-01 10:52 UTC, kaori-killer commented
![스크린샷 2024-02-01 오후 7 51 41](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/2d0f8d76-3050-43aa-93e6-7e56b599a119)

저는 공지사항 부분에서 왜 이미지가 안 나올까요?

2024-02-01 10:59 UTC, kaori-killer commented
구현하느라 넘넘 수고했어요~! 👍 공지사항 페이지에서 이미지 안 나오는 것만 수정하면 merge할게요!

이건 나중에 테스크로 추가해서 수정합니다 ⬇️

나중에 수정할 점은 
-[] 부스 상세 페이지, 이미지 사이즈가 크다. 
-[] 부스 상세 페이지, 이미지끼리 간격이 넓다.
-[] 부스 상세 페이지, 데이터를 백엔드에서 받아온다.
-[] DetailedMapPage.tsx에 컴포넌트가 여러 개 몰려있다. 파일 분리가 필요해보인다.

2024-02-01 11:16 UTC, kaori-killer commented
console 창의 오류를 보면 속성 값으로 boolean을 사용하지 말고 string을 사용하라고 나와 있습니다. shadow의 값을 string으로 변경해보세요.

![스크린샷 2024-02-01 오후 8 15 39](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/b2d7b688-ae33-49ea-823f-99f34c29e548)

2024-02-01 11:17 UTC, kaori-killer commented
console 창의 오류를 보면 속성 값으로 boolean을 사용하지 말고 string을 사용하라고 나와 있습니다. shadow의 값을 string으로 변경해보세요.

![스크린샷 2024-02-01 오후 8 15 39](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/b2d7b688-ae33-49ea-823f-99f34c29e548)

2024-02-01 11:52 UTC, snsdl0905 commented
> ![스크린샷 2024-02-01 오후 7 51 41](https://private-user-images.githubusercontent.com/75800958/301478481-2d0f8d76-3050-43aa-93e6-7e56b599a119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODg0MDMsIm5iZiI6MTcwNjc4ODEwMywicGF0aCI6Ii83NTgwMDk1OC8zMDE0Nzg0ODEtMmQwZjhkNzYtMzA1MC00M2FhLTkzZTYtN2U1NmI1OTlhMTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDExNDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNTE0N2IxZmE0ZmU4MDI2MTAwOTIzZDNkZmQ3ZTNjODAyYTY1MDQ5MWI0OGEyNGI4M2Y4MWYwN2VlZjIzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KIwJEkzYuKgTjVpd34kpdNSRUO1Dg2xdQOaP36wGBpU)
> 
> 1. 공지사항 부분에서 이미지가 왜 안 나올까요?
> 2. 공지사항은 개발이 끝난 줄 알았는데 어떤 걸 수정한 건가요?

1. 백엔드 API명세서에는 temp.jpg 이런 데이터가 들어가있길래 존재하는 이미지가 아니여서 안나온다고 생각했습니다.

2024-02-02 02:08 UTC, kaori-killer approved these changes
수고했어요!

2024-02-02 02:16 UTC, merged