Develop
INU-CapstoneDesign/INU-Festival-FE pull request #90
Opened 2024-02-21 00:15 UTC by snsdl0905

# 해결햐려는 문제가 무엇인가요? 🤔

* 필터를 변경했을 때 부스에 맞게 마커가 변경된다.
* 이미지 슬라이더들에서 마지막 이미지가 끝까지 보이지 않는 경우가 있다.
* 마커를 눌렀을 때 클릭한 마커의 부스만 리스트에 출력된다.

# 어떻게 해결하셨나요? 🔑

* 기존의 마커 배열이 제대로 비워지도록 수정했다.
* 보이지 않는 이미지 슬라이더에 slidesOffsetAfter을 추가했다.

# 어떤 부분을 리뷰 받았으면 좋겠나요? 🛠️

* 요일에 따라 마커가 잘 바뀌고 있는 지 봐주세요.

# 추가로 남길 메모가 있으신가요? 📝

* 마커를 클릭했을 때 BoothList로 클릭된 마커의 booth정보만 넘기는 것은 제대로 작동하지 않습니다. 해결하는대로 마저 커밋하겠습니다.
* 이미지 슬라이더가 화면의 크기에 따라 보여주는 이미지의 개수가 달라질 때, 이미지의 순서가 변경되지 않는 지 확인했습니다. 아래에 화면 첨부하겠습니다.

## Attachment 📸

* 이번 MR의 Front 동작의 이해를 돕는 GIF 파일 첨부!
* 리뷰어의 이해를 돕기 위한 모듈/클래스 설계에 대한 Diagram 포함!
![Feb-19-2024 21-03-00](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/105384780/dded98c4-bc7e-484f-a2d7-7cf3acb956d6)

![Feb-21-2024 09-14-43](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/105384780/e620808f-3d63-4105-8e6e-22c516d924af)

2024-02-21 05:03 UTC, snsdl0905 commented
마커를 클릭했을 때 클릭한 부스만 목록에 보이도록 수정했습니다. 

하지만 아직 몇가지 문제점이 있는 것 같습니다.

마커를 클릭했을 때, 동일한 필터를 누르는 것으로는 다시 전체 목록이 보이지 않습니다. 다시 목록을 보기 위해서 < 버튼이라도 만드는 것이 좋을까요? 아니면 배경을 눌렀을 때 다시 목록을 보이게 하는 것이 좋을까요?

그리고 Map에 filteredBooths도 state로 관리하게 하도록 추가해서인지 콘솔창에 Maximum update depth exceeded 라는 경고 문구가 뜹니다. 이 부분도 조금 더 수정이 필요할 것 같습니다.

![Feb-21-2024 13-59-28](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/105384780/120179fe-ea2b-440d-9a46-515c70d29679)

2024-02-22 09:21 UTC, kaori-killer requested changes
지도 구현하느라 너무너무 고생 많으셨습니다 😭

# 질문
- 필터를 적용했을 때, 필터된 리스트의 개수보다 마커의 개수가 적은 이유가 무엇인가요?

# 요청
- 필터 버튼을 눌렀을 때, 비주점에, 월요일을 선택했을 때와 비주점 화요일을 선택했을 때 필터된 리스트 결과 값이 같습니다. 백엔드에서 넘겨주는 데이터를 의미있는 데이터로 바꿔야할 것 같아요. 지금은 데이터가 같다보니 필터가 제대로 동작하는지 확인하기 어렵네요 😭 특히 모든 부스가 비주점에 몰려있는데, 이 부분도 개선이 필요할 것 같아요!

# 답변
- Maximum 에러가 발생하는 이유는, useEffect 안에서 setState를 사용하는데 state가 변경되면 useEffect가 실행되도록 무한반복이 돼서 그런 것 같습니다. 이는 MapLayer.tsx와 Map.tsx 두 곳에서 발생하는 것으로 보입니다. 이는 코드가 복잡해서 수정을 못했는데 떠오르는 해결책이 있으실까요?

2024-02-23 00:03 UTC, snsdl0905 commented
> # 질문
> * 필터를 적용했을 때, 필터된 리스트의 개수보다 마커의 개수가 적은 이유가 있을까요?
> > 백엔드에 많은 경도와 위도를 제공하지 않았어서, 아마 나머지는 저희 지도 상에 찍히지 않는 위치여서 그런 것 같습니다.
> 
> # 답변
> * Maximum 에러가 발생하는 이유는, useEffect 안에서 setState를 사용하는데 state가 변경되면 useEffect가 실행되도록 무한반복이 돼서 그런 것 같습니다. 이는 MapLayer.tsx와 Map.tsx 두 곳에서 발생하는 것으로 보입니다. 이는 코드가 복잡해서 수정을 못했는데, 떠오르는 해결책이 있으실까요?
> > 이 부분 해결과 리스트 하나에서 배경부분 클릭하면 여러개 다시 보여주는 것 구현중인데.. 잘 모르겠어요ㅎㅎ 오늘까지는 해결해보겠습니다.

2024-02-23 07:00 UTC, kaori-killer commented
머지하고 새로운 브렌치로 올리실래요? 아니면 이 브렌치 머지하지말고 기다릴까요?

2024-02-23 07:44 UTC, snsdl0905 commented
오늘까지 이 브랜치에 머지하겠습니다 !

2024-02-23 08:33 UTC, snsdl0905 commented
![Feb-23-2024 17-31-11](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/105384780/e4ce76f6-4b7a-45a9-9f10-cf18e361de08)

수정했습니다! 

* 마커가 선택된 상태에서 지도를 누르면 이 전의 목록으로 돌아갑니다. 혹시 의도대로 동작되지 않는 부분이 있다면 말해주세요!
* filteredBooth를 state로 관리하지 않는게 좋을 것 같아서 수정했습니다. maximum 에러도 사라진 것 같습니다.

2024-02-23 09:07 UTC, snsdl0905 commented
![Feb-23-2024 17-59-10](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/105384780/195acf14-3182-4dec-b157-660fa8e18d34)

월요일에서 마커를 선택하고 화요일로 필터를 변경하면, 부스 목록이 리셋되지 않는 문제를 발견했습니다. 마커를 클릭했을 때 selectedBooth라는 변수로 저장해놓고, 지도의 다른 부분을 클릭했을 때만 해제되게 했기 때문입니다. 

  useEffect(() => {
    setSelectedBooth(null);
  }, filteredBooths);

따라서 필터가 달라졌을 때 selectedBooth를 없애는 코드가 Map파일이나 MapLayer파일에 추가되어야하는데, 수정한 결과 경고가 발생합니다.

2024-02-23 14:56 UTC, kaori-killer reviewed
HeaderContainer라는 스타일 컴포넌트에서 shadow라는 이름의 props를 쓰고 있습니다.  이는 실제로 있는 props가 아니라 직접 정의한 이름이기 때문에 콘솔에 에러가 발생합니다.  `unknown prop`이라고 나옵니다.  이런 건 이름 앞에 $를 붙이면 에러가 사라집니다.

MapInfoBottom 컴포넌트의 showinstruction도 마찬가지로 수정이 필요해 보입니다!

```javascript
const HeaderContainer = styled.div <{ $shadow: string }>`

box-shadow: ${(props) => (props.$shadow === 'true' ? '0px 0.3rem 0.3rem 0px rgba(0, 0, 0, 0.05)' : 'none')};


<HeaderContainer $shadow={shadow}>
```

2024-02-23 14:56 UTC, kaori-killer commented on src/components/Map/MapLayer.tsx
> +  }, filteredBooths);
useEffect를 사용할 때 의존성 배열 없이 사용하고 있습니다.

다음과 같이 수정해야 할 것 같아요!

```javascript
  useEffect(() => {
    setSelectedBooth(null);
  }, [filteredBooths]);
```

2024-02-23 15:03 UTC, kaori-killer commented
저는 마커를 클릭했을 때, 마커에 해당하는 부스가 나오지 않는데 버그일까요?

![PR의영](https://github.com/INU-CapstoneDesign/INU-Festival-FE/assets/75800958/6b8e6c88-9314-4763-99fa-7a6126faaaf9)

2024-02-23 23:10 UTC, snsdl0905 commented
[filteredBooths]를 넘기는 것으로 수정해서 부스가 제대로 안나왔던 것 같습니다. 부스를 클릭했을 때 목록이 제대로 나오도록 하는 것과, props 문제 말씀해주신 것 수정했습니다!

2024-02-24 13:12 UTC, merged